version: "3.5"
services:
  rena-server:
    build: .
    container_name: rena-server-container
    init: true
    ports:
      - 80:3000
    networks:
      - rena
  # rena-mongodb:
  #   container_name: rena-mongodb
  #   image: mongo:4.4
  #   restart: unless-stopped
  #   ports:
  #     - '27017:27017'
  #   expose:
  #     - 27017
  #   volumes:
  #     - .mongodb:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ellohim023
  #     MONGO_INITDB_ROOT_PASSWORD: Leonov023
  #     MONGO_INITDB_DATABASE: The-Worker-Hub
  #     MONGODB_DATA_DIR: /data/db
  #     MONDODB_LOG_DIR: /dev/null
  #   command: mongod
  #   networks:
  #     - pph
networks:
  rena:
    driver: bridge