version: "3.5"
services:
  rena-server:
    build: .
    container_name: rena-server-container
    restart: unless-stopped
    init: true
    ports:
      - 3000:3000
    networks:
      - rena
    volumes:
      - ./storage:/usr/src/app/storage
networks:
  rena:
    driver: bridge