version: "3.5"
services:
  rena-server:
    build: .
    container_name: rena-server-container
    restart: unless-stopped
    init: true
    ports:
      - 3000:3000
    network_mode: "host"
    volumes:
      # - ./:/usr/src/app
      - ./storage:/usr/src/app/storage