version: "3.5"
services:
  rena-server:
    build: .
    container_name: rena-server-container
    init: true
    ports:
      - 3000:3000
    networks:
      - rena
networks:
  rena:
    driver: bridge